CREATE TABLE `TRAIN` (
  `TRAIN_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORIGIN` int(11) NOT NULL,
  `DESTINATION` int(11) NOT NULL,
  `IIME_DAY` varchar(3) NOT NULL,
  `WKD_BIN` int(1) NOT NULL,
  PRIMARY KEY (TRAIN_ID),
  FOREIGN KEY (ORIGIN) REFERENCES STATION (STATION_ID),
  FOREIGN KEY (DESTINATION) REFERENCES STATION (STATION_ID)
);

CREATE TABLE `STATION` (
  `STATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CITY` varchar(33) NOT NULL,
  `STATE` varchar(2) NOT NULL,
  PRIMARY KEY (STATION_ID)
);

CREATE TABLE `STOPS_AT` (
  `STATION_ID` int(11) NOT NULL,
  `TRAIN_ID` int(11) NOT NULL,
  `ARRIVAL` time(0) NOT NULL,
  `DEPARTURE` time(0) NOT NULL,
  FOREIGN KEY (STATION_ID) REFERENCES STATION (STATION_ID),
  FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN (TRAIN_ID),
  PRIMARY KEY (STATION_ID, TRAIN_ID)
);

CREATE TABLE `SEGMENT` (
  `SEGMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `NORTH_END` int(11) NOT NULL,
  `SOUTH_END` int(11) NOT NULL,
  `FARE` float(6,2) NOT NULL,
  `TRAVEL_TIME` time(0) NOT NULL,
  FOREIGN KEY (NORTH_END) REFERENCES STATION (STATION_ID),
  FOREIGN KEY (SOUTH_END) REFERENCES STATION (STATION_ID),
  PRIMARY KEY (SEGMENT_ID)
);

CREATE TABLE `SPECIAL_FARE` (
  `TYPE` varchar(15) NOT NULL,
  `FACTOR` float(4,3) NOT NULL,
  PRIMARY KEY (TYPE)
);

CREATE TABLE `RESERVATION` (
  `RESERVATION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PASSENGER_ID` int(11) NOT NULL,
  `RES_DATE` date NOT NULL,
  `PAYMENT_METHOD` varchar(10) NOT NULL,
  PRIMARY KEY (RESERVATION_ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID)
);

CREATE TABLE `SEATS_FREE` (
  `SEGMENT_ID` int(11) NOT NULL,
  `TRAIN_ID` int(11) NOT NULL,
  `DATE` date NOT NULL,
  `SEATS_FREE` int(3) NOT NULL,
  FOREIGN KEY (SEGMENT_ID) REFERENCES SEGMENT (SEGMENT_ID),
  FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN (TRAIN_ID),
  PRIMARY KEY (SEGMENT_ID, TRAIN_ID, DATE)
);

CREATE TABLE `PASSENGER` (
  `PASSENGER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(30) NOT NULL,
  `LAST NAME` varchar(30) NOT NULL,
  `PHONE_NUMBER` varchar(10) NOT NULL,
  `EMAIL` varchar(30) NOT NULL,
  PRIMARY KEY (PASSENGER_ID)
);

CREATE TABLE `TRIP` (
  `TRIP_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TRAIN_ID` int(11) NOT NULL,
  `PASSENGER_ID` int(11) NOT NULL,
  `ORIGIN` int(11) NOT NULL,
  `DESTINATION` int(11) NOT NULL,
  `TRIP_DATE` date NOT NULL,
  `PRICE` float(6,2) NOT NULL,
  PRIMARY KEY (TRIP_ID),
  FOREIGN KEY (TRAIN_ID) REFERENCES TRAIN (TRAIN_ID),
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER (PASSENGER_ID),
  FOREIGN KEY (ORIGIN) REFERENCES STATION (STATION_ID),
  FOREIGN KEY (DESTINATION) REFERENCES STATION (STATION_ID)
);
