DELIMITER //

CREATE PROCEDURE DELETE_ALL()
BEGIN

  DELETE FROM SPECIAL_FARE;
  DELETE FROM TRIP;
  DELETE FROM SEATS_FREE;
  DELETE FROM RESERVATION;
  DELETE FROM PASSENGER;
  DELETE FROM SEGMENT;
  DELETE FROM STOPS_AT;
  DELETE FROM TRAIN;
  DELETE FROM STATION;

END //

DELIMITER ;
