DELIMITER //

CREATE PROCEDURE FILL_STOPS_AT()
BEGIN
  DECLARE ORIGIN_ID INT(11);
  DECLARE DEST_ID INT(11);
  DECLARE CURRENT_STATION INT(11);
  DECLARE CURRENT_TRAIN INT(11);
  DECLARE LAST_TRAIN INT(11);
  DECLARE DAY_TIME VARCHAR(3);
  DECLARE WEEKDAY INT(1);
  DECLARE START_TIME TIME(0);
  DECLARE TRAVEL TIME(0);
  DECLARE ARRIVE TIME(0);
  DECLARE DEPART TIME(0);
  DECLARE ITERATOR INT(3);

  SET CURRENT_TRAIN = (SELECT MIN(TRAIN_ID) FROM S18336PRRteam1.TRAIN);
  SET LAST_TRAIN = (SELECT MAX(TRAIN_ID) FROM S18336PRRteam1.TRAIN);
  SET ITERATOR = 0;
  SET TRAVEL = 0;

  WHILE CURRENT_TRAIN <= LAST_TRAIN DO
    SET DAY_TIME = (SELECT TIME_DAY FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
    SET WEEKDAY = (SELECT WKD_BIN FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
    IF WEEKDAY = 1 THEN
      IF DAY_TIME = 'MOR' THEN
        SET START_TIME = '5:30:0';
        WHILE ITERATOR < 3 DO
          SET ARRIVE = START_TIME;
          SET ORIGIN_ID = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET DEST_ID = (SELECT DESTINATION FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET CURRENT_STATION = ORIGIN_ID;

          IF ORIGIN_ID < DEST_ID THEN
            WHILE CURRENT_STATION <= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:02:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION + 1;
            END WHILE;
          ELSE
            WHILE CURRENT_STATION >= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:02:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE SOUTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION - 1;
            END WHILE;
          END IF;

          SET ITERATOR = ITERATOR + 1;
          SET START_TIME = (SELECT ADDTIME(START_TIME, '2:00:00'));
          SET CURRENT_TRAIN = CURRENT_TRAIN + 1;
        END WHILE;
        SET ITERATOR = 0;

      ELSEIF DAY_TIME = 'AFT' THEN
        SET START_TIME = '13:00:0';
        WHILE ITERATOR < 3 DO
          SET ARRIVE = START_TIME;
          SET ORIGIN_ID = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET DEST_ID = (SELECT DESTINATION FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET CURRENT_STATION = ORIGIN_ID;

          IF ORIGIN_ID < DEST_ID THEN
            WHILE CURRENT_STATION <= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:01:30'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION + 1;
              END WHILE;
          ELSE
            WHILE CURRENT_STATION >= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:01:30'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE SOUTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION - 1;
            END WHILE;
          END IF;

          SET ITERATOR = ITERATOR + 1;
          SET START_TIME = (SELECT ADDTIME(START_TIME, '1:45:00'));
          SET CURRENT_TRAIN = CURRENT_TRAIN + 1;
        END WHILE;
        SET ITERATOR = 0;

      ELSE
        SET START_TIME = '18:45:0';
        WHILE ITERATOR < 2 DO
          SET ARRIVE = START_TIME;
          SET ORIGIN_ID = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET DEST_ID = (SELECT DESTINATION FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET CURRENT_STATION = ORIGIN_ID;

          IF ORIGIN_ID < DEST_ID THEN
            WHILE CURRENT_STATION <= DEST_ID DO
              IF (SELECT ADDTIME(DEPART, '-24:00:00')) > 0 THEN
                SET DEPART = (SELECT ADDTIME(DEPART, '-24:00:00'));
              END IF;

              IF (SELECT ADDTIME(ARRIVE, '-24:00:00')) > 0 THEN
                SET ARRIVE = (SELECT ADDTIME(ARRIVE, '-24:00:00'));
              END IF;
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:05:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION + 1;
              END WHILE;
          ELSE
            WHILE CURRENT_STATION >= DEST_ID DO
              IF (SELECT ADDTIME(DEPART, '-24:00:00')) > 0 THEN
                SET DEPART = (SELECT ADDTIME(DEPART, '-24:00:00'));
              END IF;

              IF (SELECT ADDTIME(ARRIVE, '-24:00:00')) > 0 THEN
                SET ARRIVE = (SELECT ADDTIME(ARRIVE, '-24:00:00'));
              END IF;
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:05:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE SOUTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION - 1;
            END WHILE;
          END IF;

          SET ITERATOR = ITERATOR + 1;
          SET START_TIME = (SELECT ADDTIME(START_TIME, '2:45:00'));
          SET CURRENT_TRAIN = CURRENT_TRAIN + 1;
        END WHILE;
        SET ITERATOR = 0;

      END IF;

    ELSE
      IF DAY_TIME = 'MOR' THEN
        SET START_TIME = '3:30:0';
        WHILE ITERATOR < 3 DO
          SET ARRIVE = START_TIME;
          SET ORIGIN_ID = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET DEST_ID = (SELECT DESTINATION FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET CURRENT_STATION = ORIGIN_ID;

          IF ORIGIN_ID < DEST_ID THEN
            WHILE CURRENT_STATION <= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:02:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION + 1;
            END WHILE;
          ELSE
            WHILE CURRENT_STATION >= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:02:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE SOUTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION - 1;
            END WHILE;
          END IF;

          SET ITERATOR = ITERATOR + 1;
          SET START_TIME = (SELECT ADDTIME(START_TIME, '3:00:00'));
          SET CURRENT_TRAIN = CURRENT_TRAIN + 1;
        END WHILE;
        SET ITERATOR = 0;

      ELSEIF DAY_TIME = 'AFT' THEN
        SET START_TIME = '12:00:0';
        WHILE ITERATOR < 3 DO
          SET ARRIVE = START_TIME;
          SET ORIGIN_ID = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET DEST_ID = (SELECT DESTINATION FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET CURRENT_STATION = ORIGIN_ID;

          IF ORIGIN_ID < DEST_ID THEN
            WHILE CURRENT_STATION <= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:01:30'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION + 1;
            END WHILE;
          ELSE
            WHILE CURRENT_STATION >= DEST_ID DO
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:01:30'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE SOUTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION - 1;
            END WHILE;
          END IF;

          SET ITERATOR = ITERATOR + 1;
          SET START_TIME = (SELECT ADDTIME(START_TIME, '2:30:00'));
          SET CURRENT_TRAIN = CURRENT_TRAIN + 1;
        END WHILE;
        SET ITERATOR = 0;

      ELSE
        SET START_TIME = '20:00:0';
        WHILE ITERATOR < 2 DO
          SET ARRIVE = START_TIME;
          SET ORIGIN_ID = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET DEST_ID = (SELECT DESTINATION FROM S18336PRRteam1.TRAIN WHERE TRAIN_ID = CURRENT_TRAIN);
          SET CURRENT_STATION = ORIGIN_ID;

          IF ORIGIN_ID < DEST_ID THEN
            WHILE CURRENT_STATION <= DEST_ID DO
              IF (SELECT ADDTIME(DEPART, '-24:00:00')) > 0 THEN
                SET DEPART = (SELECT ADDTIME(DEPART, '-24:00:00'));
              END IF;

              IF (SELECT ADDTIME(ARRIVE, '-24:00:00')) > 0 THEN
                SET ARRIVE = (SELECT ADDTIME(ARRIVE, '-24:00:00'));
              END IF;
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:05:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION + 1;
            END WHILE;
          ELSE
            WHILE CURRENT_STATION >= DEST_ID DO
              IF (SELECT ADDTIME(DEPART, '-24:00:00')) > 0 THEN
                SET DEPART = (SELECT ADDTIME(DEPART, '-24:00:00'));
              END IF;

              IF (SELECT ADDTIME(ARRIVE, '-24:00:00')) > 0 THEN
                SET ARRIVE = (SELECT ADDTIME(ARRIVE, '-24:00:00'));
              END IF;
              SET DEPART = (SELECT ADDTIME(ARRIVE, '0:05:00'));
              INSERT INTO `STOPS_AT` (`STATION_ID`, `TRAIN_ID`, `ARRIVAL`, `DEPARTURE`) VALUES (CURRENT_STATION, CURRENT_TRAIN, ARRIVE, DEPART);
              SET TRAVEL = (SELECT TRAVEL_TIME FROM S18336PRRteam1.SEGMENT WHERE SOUTH_END = CURRENT_STATION);
              SET ARRIVE = (SELECT ADDTIME(TRAVEL, DEPART));
              SET CURRENT_STATION = CURRENT_STATION - 1;
            END WHILE;
          END IF;

          SET ITERATOR = ITERATOR + 1;
          SET START_TIME = (SELECT ADDTIME(START_TIME, '3:45:00'));
          SET CURRENT_TRAIN = CURRENT_TRAIN + 1;
        END WHILE;
        SET ITERATOR = 0;

      END IF;
    END IF;
  END WHILE;

END //

DELIMITER ;
