DELIMITER //

CREATE PROCEDURE FILL_SEGMENT()
BEGIN

  DECLARE ORIGIN_ID INT(11);
  DECLARE SEG_START INT(11);
  DECLARE SEG_END INT(11);

  SET ORIGIN_ID = (SELECT min(STATION_ID) FROM S18336PRRteam1.STATION);
  SET SEG_START = ORIGIN_ID;
  SET SEG_END = SEG_START + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '4.75', '0:5:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '11.5', '0:13:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '28', '0:31:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '24.25', '0:25:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '16.75', '0:16:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '10.75', '0:11:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '10.75', '0:13:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '17.5', '0:21:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '28.75', '0:36:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '16.75', '0:11:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '20.5', '0:27:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '16.75', '0:20:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '18.25', '0:32:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '11.5', '0:19:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '6.25', '0:3:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '12.25', '0:12:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '29.5', '0:23:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '28.75', '0:28:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '22.75', '0:21:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '13', '0:14:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '24.25', '0:23:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '26.5', '0:29:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '12.25', '0:12:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '19.75', '0:15:0');

  SET SEG_START = SEG_START + 1;
  SET SEG_END = SEG_END + 1;

  INSERT INTO `SEGMENT` (`NORTH_END`, `SOUTH_END`, `FARE`, `TRAVEL_TIME`) VALUES (SEG_START, SEG_END, '10.75', '0:17:0');

END //

DELIMITER ;
