DELIMITER //

/*
* This procedure takes a passengers origin station, their destination, the approximate time they wish to travel, and the
* date of travel. With all this information, it determines all trains that have available seating. This output
* will never have more than 3 choices. After the passenger chooses their desired train, another procedure handles the rest.
*/
CREATE PROCEDURE GET_AVAILABLE_TRAINS(IN LOCAL_ORIGIN INT(11), IN DESTIN INT(11), IN LOCAL_TIME_DAY VARCHAR(3), IN LOCAL_DATE DATE, OUT TRAIN_ID1 INT(11), OUT TRAIN_ID2 INT(11), OUT TRAIN_ID3 INT(11))
BEGIN
	DECLARE DAY_WEEK_BINARY INT(1);
	
	DECLARE DIRECTION INT(11);

	IF (SELECT WEEKDAY(LOCAL_DATE)) <= 4 THEN
	   SET DAY_WEEK_BINARY = 1;
	END IF;

	IF (SELECT WEEKDAY(LOCAL_DATE)) > 4 THEN
	   SET DAY_WEEK_BINARY = 0;
	END IF;

	IF LOCAL_ORIGIN - DESTIN < 0 THEN
	   SET DIRECTION = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN ORDER BY ORIGIN LIMIT 1);
	END IF;

	IF LOCAL_ORIGIN - DESTIN > 0 THEN
	   SET DIRECTION = (SELECT ORIGIN FROM S18336PRRteam1.TRAIN ORDER BY ORIGIN DESC LIMIT 1);
	END IF;
	
	SET TRAIN_ID1 = (SELECT TRAIN_ID FROM S18336PRRteam1.TRAIN WHERE TIME_DAY = LOCAL_TIME_DAY AND WKD_BIN = DAY_WEEK_BINARY AND ORIGIN = DIRECTION LIMIT 1);
	SET TRAIN_ID2 = (SELECT TRAIN_ID FROM S18336PRRteam1.TRAIN WHERE TIME_DAY = LOCAL_TIME_DAY AND WKD_BIN = DAY_WEEK_BINARY AND ORIGIN = DIRECTION LIMIT 1 OFFSET 1);
	SET TRAIN_ID3 = (SELECT TRAIN_ID FROM S18336PRRteam1.TRAIN WHERE TIME_DAY = LOCAL_TIME_DAY AND WKD_BIN = DAY_WEEK_BINARY AND ORIGIN = DIRECTION LIMIT 1 OFFSET 2);

        SET @CHECK_BIT1 = (SELECT CHECK_FREE_SEATS(LOCAL_ORIGIN, DESTIN, TRAIN_ID1, LOCAL_DATE));

        IF @CHECK_BIT1 = 0 THEN
           SET TRAIN_ID1 = 0;
        END IF;

        SET @CHECK_BIT2 = (SELECT CHECK_FREE_SEATS(LOCAL_ORIGIN, DESTIN, TRAIN_ID2, LOCAL_DATE));

        IF @CHECK_BIT2 = 0 THEN
           SET TRAIN_ID2 = 0;
        END IF;

	SET @CHECK_BIT3 = (SELECT CHECK_FREE_SEATS(LOCAL_ORIGIN, DESTIN, TRAIN_ID3, LOCAL_DATE));

	IF @CHECK_BIT3 = 0 THEN
	   SET TRAIN_ID3 = 0;
	END IF;
END //
DELIMITER ;
