DELIMITER //

CREATE PROCEDURE GET_PRICE(IN ORIGIN INT(11), IN DEST INT(11), IN DIS_BIN BIT, IN MILIT_BIN BIT, IN AGE INT(1), IN PET_NUM INT, IN TRIP_DATE DATE, IN RES_DATE DATE, OUT PRICE DOUBLE(6,2))
BEGIN

  DECLARE NORTH INT(11);
  DECLARE SOUTH INT(11);
  DECLARE SEGMENT_CURSOR INT(11);
  DECLARE FULL_FARE FLOAT(6,2);
  DECLARE SEGMENT_FARE FLOAT(6,2);
  DECLARE PET_FEE FLOAT(6,2);
  DECLARE DAYS_UNTIL INT(3);

  IF ORIGIN < DEST THEN
    SET NORTH = ORIGIN;
    SET SOUTH = DEST;
  ELSE
    SET NORTH = DEST;
    SET SOUTH = ORIGIN;
  END IF;

  SET SEGMENT_CURSOR = NORTH;
  SET FULL_FARE = 0;
  SET SEGMENT_FARE = 0;

  WHILE (SEGMENT_CURSOR != SOUTH AND SEGMENT_CURSOR < SOUTH) DO
    SET SEGMENT_FARE = (SELECT FARE FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = SEGMENT_CURSOR);
    SET FULL_FARE = FULL_FARE + SEGMENT_FARE;
    SET SEGMENT_CURSOR = SEGMENT_CURSOR + 1;
  END WHILE;

  IF DIS_BIN = 1 THEN
    SET FULL_FARE = (FULL_FARE * 0.9);
  END IF;

  IF MILIT_BIN = 1 THEN
    SET FULL_FARE = (FULL_FARE * 0.9);
  END IF;

  IF AGE = '0' THEN
    SET FULL_FARE = (FULL_FARE * 0.5);
  ELSEIF AGE = '2' THEN
    SET FULL_FARE = (FULL_FARE * 0.85);
  END IF;

  SET DAYS_UNTIL = (SELECT DATEDIFF(TRIP_DATE, RES_DATE));

  IF DAYS_UNTIL <= '3' THEN
    SET FULL_FARE = (FULL_FARE * 1.4);
  ELSEIF DAYS_UNTIL <= '5' THEN
    SET FULL_FARE = (FULL_FARE * 1.25);
  ELSEIF DAYS_UNTIL <= '10' THEN
    SET FULL_FARE = (FULL_FARE * 1.15);
  ELSEIF DAYS_UNTIL <= '15' THEN
    SET FULL_FARE = (FULL_FARE * 1.1);
  ELSEIF DAYS_UNTIL <= '30' THEN
    SET FULL_FARE = (FULL_FARE * 1.05);
  END IF;

  SET PET_FEE = (25 * PET_NUM);
  SET FULL_FARE = (FULL_FARE + PET_FEE);
  SET PRICE = FULL_FARE;

END //

DELIMITER ;
