DELIMITER //

/*
* After a passenger descides which train they want to take on a particular date and time,
* this procedure is responsible for subtracting 1 from the number of seats free on the train
* along the passenger's intended route/trip. This is accomplished by iterating through
* the SEATS_FREE table by segment_id. The segment_id corresponds to the segment for their
* trip. 
*/

CREATE PROCEDURE OCCUPY_FREE_SEAT(LOCAL_ORIGIN INT(11), LOCAL_DESTIN INT(11), LOCAL_TRAIN_ID INT(11), LOCAL_DATE DATE)
BEGIN
        DECLARE LOCAL_SEGMENT_ID INT(11);
        DECLARE LOCAL_NORTH_END INT(11);
        DECLARE LOCAL_SOUTH_END INT(11);
        DECLARE DIRECTION_INT INT(11);
        DECLARE LOCAL_SEATS_FREE INT(11);
        SET DIRECTION_INT = LOCAL_ORIGIN - LOCAL_DESTIN;

        IF DIRECTION_INT < 0 THEN
           SET LOCAL_SEGMENT_ID = (SELECT SEGMENT_ID FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = LOCAL_ORIGIN);
           SET LOCAL_SOUTH_END = (SELECT SOUTH_END FROM S18336PRRteam1.SEGMENT WHERE SEGMENT_ID = LOCAL_SEGMENT_ID);

           WHILE LOCAL_SOUTH_END != LOCAL_DESTIN+1 DO

                 SET LOCAL_SEATS_FREE = (SELECT `SEATS FREE` FROM S18336PRRteam1.SEATS_FREE WHERE SEGMENT_ID = LOCAL_SEGMENT_ID AND TRAIN_ID = LOCAL_TRAIN_ID AND `DATE` = LOCAL_DATE) - 1;

                 UPDATE S18336PRRteam1.SEATS_FREE SET `SEATS FREE` = LOCAL_SEATS_FREE WHERE SEGMENT_ID = LOCAL_SEGMENT_ID AND TRAIN_ID = LOCAL_TRAIN_ID AND `DATE` = LOCAL_DATE;

                 SET LOCAL_SEGMENT_ID = LOCAL_SEGMENT_ID + 1;
                 SET LOCAL_SOUTH_END = (SELECT SOUTH_END FROM S18336PRRteam1.SEGMENT WHERE SEGMENT_ID = LOCAL_SEGMENT_ID);
           END WHILE;
        END IF;

        IF DIRECTION_INT > 0 THEN
           SET LOCAL_SEGMENT_ID = (SELECT SEGMENT_ID FROM S18336PRRteam1.SEGMENT WHERE NORTH_END = LOCAL_ORIGIN);
           SET LOCAL_NORTH_END = (SELECT NORTH_END FROM S18336PRRteam1.SEGMENT WHERE SEGMENT_ID = LOCAL_SEGMENT_ID);

           WHILE LOCAL_NORTH_END != LOCAL_DESTIN+1 DO

                 SET LOCAL_SEATS_FREE = (SELECT `SEATS FREE` FROM S18336PRRteam1.SEATS_FREE WHERE SEGMENT_ID = LOCAL_SEGMENT_ID AND TRAIN_ID = LOCAL_TRAIN_ID AND `DATE` = LOCAL_DATE) - 1;

           1      UPDATE S18336PRRteam1.SEATS_FREE SET `SEATS FREE` = LOCAL_SEATS_FREE WHERE SEGMENT_ID = LOCAL_SEGMENT_ID AND TRAIN_ID = LOCAL_TRAIN_ID AND `DATE` = LOCAL_DATE;

                 SET LOCAL_SEGMENT_ID = LOCAL_SEGMENT_ID + 1;
                 SET LOCAL_NORTH_END = (SELECT NORTH_END FROM S18336PRRteam1.SEGMENT WHERE SEGMENT_ID = LOCAL_SEGMENT_ID);
           END WHILE;
        END IF;
END //
DELIMITER ;
